### ISSUE TITLE
The serve() method will get stuck

### ISSUE THREAD

**Issue by liyuefeng** [explodinglabs/jsonrpcserver#265] opened 2023-05-29 08:43 UTC
window 11
release：5.0.9
code：
serve()

I find self.__shutdown_request is always False and serve can not start
                while not self.__shutdown_request:
                    ready = selector.select(poll_interval)
                    # bpo-35017: shutdown() called during select(), exit immediately.
                    if self.__shutdown_request:
                        break
                    if ready:
                        self._handle_request_noblock()

**Comment by bcb** [comment] 2023-05-29 18:49
Thanks for reporting. 

The serve function is only meant for basic testing. For anything more you should use `dispatch`. 

This will be fixed in version 6. Closing as a duplicate of #264

**Closed by bcb** 2023-05-29 18:49 UTC
